### ISSUE TITLE
image translation

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/server#59]
Hi, Ilya and the Team!

I've tried to follow the README and tried to translate the images but it's not working somewhat.

Could you check the README?

Chinese contributors also mentioned that they had the same problem.

https://github.com/javascript-tutorial/zh.javascript.info/issues/747

**Comment by iliakan** [comment]
Hi, thanks for making the issue!

What doesn’t work exactly, could you elaborate please?

**Comment by iliakan** [comment]
Hello?

**Comment by iliakan** [comment]
@Violet-Bora-Lee

**Comment by Violet-Bora-Lee** [comment]
Hello. I was trying to find the exact cause, but I couldn't find it, so I couldn't leave any more comments.

The same phenomenon happened in the Chinese project, so they translated the svg there right away, so could you follow the lead me and check if it is reproduced?

**Comment by Violet-Bora-Lee** [comment]
Or I think it's not a bad idea to translate SVG files manually. In order to do that, the README file need to be updated

**Comment by iliakan** [comment]
Ok, I just wanted to hear what exactly isn't working. Will ask them then.

**Comment by Violet-Bora-Lee** [comment]
Thanks!

**Comment by leviding** [comment]
This is a test of images.yml:

```yml
try-catch-flow.svg:
  "Begin":
    text: "开始"
    position: "center"
  "No Errors":
    text: "没有 Error"
    position: "center"
  "An error occured in the code":
    text: "代码中出现了一个 error"
    position: "center"
  "// code...": "// код..."
  "Ignore catch block":
    text: "忽略 catch 代码块"
    position: "center"
  "Ignore the rest of try":
    text: "忽略 try 代码块中余下的内容"
    position: "center"
  "Execute catch block":
    text: "执行 catch 代码块"
    position: "center"

recursion-pow.svg:
  "Yes":
    text: "是"
    position: "center"
  "No":
    text: "否"
  "recursive call until n==1": "递归调用直到 n==1"
```

Thanks!
